export const Materials = {
	bronze: {
		name: "Bronze",
		type: "currency",
		curr: true,
		img_url: "./images/materials/curr_bronze.jpg",
		color: "#674d56",
		tick: 6,
		tickTop: -1,
		p: 100 - ((1 / 5) * 100),
		qty: 0,
	},
	silver: {
		name: "Silver",
		type: "currency",
		curr: true,
		img_url: "./images/materials/curr_silver.jpg",
		color: "#969696",
		tick: 6,
		tickTop: -1,
		p: 100 - ((1 / 120) * 100),
		qty: 0,
	},
	gold: {
		name: "Gold",
		type: "currency",
		curr: true,
		img_url: "./images/materials/curr_gold.jpg",
		color: "#ffe946",
		tick: 6,
		tickTop: -1,
		p: 100 - ((1 / 240) * 100),
		qty: 0,
	},
	mythril: {
		name: "Mythril",
		type: "currency",
		curr: true,
		img_url: "./images/materials/curr_mythril.jpg",
		color: "#fc5044",
		tick: 6,
		tickTop: -1,
		p: 100 - ((1 / 1080) * 100),
		qty: 0,
	},

	lollipop: {
		name: "Lollipop",
		type: "material",
		img_url: "./images/materials/mat_pop.jpg",
		color: "#ffe946",
		tick: 10,
		tickTop: -3,
		p: 100 - ((1 / 100) * 100),
		qty: 0,
	},
	gun: {
		name: "Gun",
		type: "material",
		img_url: "./images/materials/mat_gun.jpg",
		color: "#ffe946",
		tick: 10,
		tickTop: -3,
		p: 100 - ((1 / 100) * 100),
		qty: 0,
	},
	axe: {
		name: "Axe",
		type: "material",
		img_url: "./images/materials/mat_axe.jpg",
		color: "#ffe946",
		tick: 10,
		tickTop: -3,
		p: 100 - ((1 / 100) * 100),
		qty: 0,
	},
	ship: {
		name: "Spaceship",
		type: "material",
		img_url: "./images/materials/mat_ship.jpg",
		color: "#ffe946",
		tick: 10,
		tickTop: -3,
		p: 100 - ((1 / 100) * 100),
		qty: 0,
	},
};

export default Materials;